version: "3.8"

volumes:
  dbmovies_data:
  apimovies_files:

networks:
  rotten_potatoes_ms:
    driver: bridge

services:
  apimovies:
    image: gfagundes/movies:${TAG_IMAGE_VERSION_MOVIES}
    build:
      context: ./src
      dockerfile: ./Dockerfile
    depends_on:
      - dbmovies
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@dbmovies:27017/admin
    volumes:
      - apimovies_files:/data/src
    networks:
      - rotten_potatoes_ms

  dbmovies:
    image: mongo:${TAG_IMAGE_VERSION_DATABASE_MONGO}
    networks:
      - rotten_potatoes_ms
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - dbmovies_data:/data/db 